name = "mastra-test2"
main = "src/mastra/index.ts" # Change to your actual entry point file path
compatibility_flags = [ "nodejs_compat" ]
[build]
command = "npx esbuild src/index.js --bundle --conditions=node --platform=node"